version: '3'

volumes:
    db_data:
    logs:
        driver: local

services:
    db:
        image: mysql:5.7
        restart: always
        container_name: slim-db
        environment:
            MYSQL_ROOT_PASSWORD: rootdockerpw
            MYSQL_DATABASE: slim_database
            MYSQL_USER: dockeruser
            MYSQL_PASSWORD: dockerpw
        ports:
            - 9906:3306
        volumes:
            - db_data:/var/lib/mysql
            - ./sql/docker-dump.sql:/docker-entrypoint-initdb.d/docker-dump.sql
    
    # http://localhost:8080
    webserver:
        #image: php:7-alpine
        container_name: slim-webserver
        restart: always
        working_dir: /var/www
        command: php -S 0.0.0.0:8080 -t public
        environment:
            docker: "true"
            #APP_DB_HOST: db:3306
            APP_DB_NAME: slim_database
            APP_DB_USER: dockeruser
            APP_DB_PASSWORD: dockerpw
        build:
            context: ./
            dockerfile: Dockerfile
        ports:
            - 8080:8080
        volumes:
            - .:/var/www
            - logs:/var/www/logs
        depends_on:
            - db
    
    # http://localhost:9999
    adminer:
        image: adminer
        container_name: slim-adminer
        restart: always
        ports:
            - 9999:8080
